name = "aqimon"
compatibility_date = "2022-11-02"
account_id = "<cloudflare_account_id>"
workers_dev = true
usage_model = 'bundled'
kv_namespaces = [
  { binding = "STATE", id = "<cloudflare_workers_kv_namesapce_id>" },
]

[build]
command = "make"

[triggers]
crons = ["*/30 * * * *"]

[vars]
SENSOR_IDS = "67381,62285" # comma delimited list of sensor ids
HOSTNAME = "my.workers.dev.hostname"
PUSHOVER_APPLICATION_TOKEN = ""
PUSHOVER_USER_TARGET = ""
LOCAL_IANA_TIME_ZONE = "America/New_York"
PURPLE_AIR_READ_API_KEY = "gotta email them to get one of these"
